### ISSUE TITLE
 Sponsor logo for Caravan does not show up on blog post

### ISSUE THREAD

**Issue by agrant3d** [mtlpy/mtlpyweb#8] opened 2014-05-02 00:42 UTC
Tried to add Caravan as a sponsor to http://montrealpython.org/en/2013/11/python-project-night-ix-soiree-projets-python-ix/ but their logo gave a 404.
Previous Issue Location:https://github.com/mtlpy/mtlpy-django-abandoned/issues/15

**Comment by mlhamel** [comment] 2015-04-02 19:54
duplicate of #22

**Closed by mlhamel** 2015-04-02 19:54 UTC
